{% set version = "5.0.0" %}

package:
  name: pyscipopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PySCIPOpt/archive/v{{ version }}.tar.gz
  sha256: 2109b24c81887523b2cde1cb450af3ae5b8e2e96604234c255315fab3cada6be

build:
  number: 1
  script: '"${PYTHON}" -m pip install .'  # [unix]
  script: '"%PYTHON%"  -m pip install .'  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - cython >=3
  run:
    - python

test:
  imports:
    - pyscipopt
    - pyscipopt.scip
  commands:
    - python -c "import pyscipopt.scip; pyscipopt.scip.Model()"

about:
  home: https://github.com/scipopt/PySCIPOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interface from Python to the SCIP Optimization Suite
  doc_url: https://scipopt.github.io/PySCIPOpt/docs/html/

extra:
  recipe-maintainers:
    - ju-manns
    - AntoinePrv
    - pokutta
    - fschloesser
