{% set version = "3.1.2" %}

package:
  name: pyscipopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PySCIPOpt/archive/v{{ version }}.tar.gz
  sha256: b50b2f94a80d040410904a09f5273e6611e51ccc190da6358b9cff2fd6215cee

build:
  number: 0
  skip: true  # [win]
  script: '"${PYTHON}" -m pip install --no-deps .'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - scip
    - python
    - pip
    - cython >=0.29.21
  run:
    - python

test:
  imports:
    - pyscipopt
    - pyscipopt.scip
  commands:
    - python -c 'import pyscipopt.scip; pyscipopt.scip.Model()'

about:
  home: https://github.com/scipopt/PySCIPOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interface from Python to the SCIP Optimization Suite
  doc_url: https://scipopt.github.io/PySCIPOpt/docs/html/

extra:
  recipe-maintainers:
    - AntoinePrv
    - pokutta
    - fschloesser
