{% set version = "5.6.0" %}

package:
  name: pyscipopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PySCIPOpt/archive/v{{ version }}.tar.gz
  sha256: 3e618046ead72a6c77e53a4d933682a8ff8432c79c149f8c924d99401aaa5eb4

build:
  number: 0
  script: '"${PYTHON}" -m pip install --no-deps .'  # [unix]
  script: '"%PYTHON%"  -m pip install --no-deps .'  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3                              # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - scip >=9
    - python
    - pip
    - cython >=3
    - setuptools
  run:
    - python
    - numpy >=1.16.0

test:
  imports:
    - pyscipopt
    - pyscipopt.scip
  commands:
    - python -c "import pyscipopt.scip; pyscipopt.scip.Model()"

about:
  home: https://github.com/scipopt/PySCIPOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interface from Python to the SCIP Optimization Suite
  doc_url: https://scipopt.github.io/PySCIPOpt/docs/html/

extra:
  recipe-maintainers:
    - ju-manns
    - AntoinePrv
    - pokutta
    - fschloesser
