{% set version = "3.1.1" %}

package:
  name: pyscipopt
  version: {{ version }}

source:
  url: https://github.com/scipopt/PySCIPOpt/archive/v{{ version }}.tar.gz
  sha256: 64cd9d537b7adf5c15e4b0f93e16bca7191719eab7060132562cba9b35b431a9

build:
  number: 0
  skip: true  # [win]
  script: '"${PYTHON}" -m pip install --no-deps .'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - scip
    - python
    - pip
    - cython >=0.29.21
  run:
    - python

test:
  imports:
    - pyscipopt
    - pyscipopt.scip
  commands:
    - python -c 'import pyscipopt.scip; pyscipopt.scip.Model()'

about:
  home: https://github.com/scipopt/PySCIPOpt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interface from Python to the SCIP Optimization Suite
  doc_url: https://scipopt.github.io/PySCIPOpt/docs/html/

extra:
  recipe-maintainers:
    - AntoinePrv
    - pokutta
    - fschloesser
