schema_version: 1

context:
  version: "6.1.0"

package:
  name: pyscipopt
  version: ${{ version }}

source:
  url: https://github.com/scipopt/PySCIPOpt/archive/v${{ version }}.tar.gz
  sha256: 8c4541fcd126ac31a6e2166de93b8fd837f73af54e640d3b4a2dad3818002ce3
  patches:
    - 0001-Fix-list-type.patch

build:
  number: 0
  script: >-
    "${{ PYTHON }}" -m pip install --no-deps --no-build-isolation .

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython >=3
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - scip ==10
    - python
    - pip
    - cython >=3
    - setuptools
  run:
    - python
    - numpy >=1.16.0

tests:
  - python:
      imports:
        - pyscipopt
        - pyscipopt.scip
  - script:
      - python -c "import pyscipopt.scip; pyscipopt.scip.Model()"

about:
  license: MIT
  license_file: LICENSE
  summary: Interface from Python to the SCIP Optimization Suite
  homepage: https://github.com/scipopt/PySCIPOpt
  documentation: https://scipopt.github.io/PySCIPOpt/docs/html/

extra:
  recipe-maintainers:
    - ju-manns
    - AntoinePrv
    - pokutta
    - fschloesser
